### ISSUE TITLE
How to get VENDOR_ID = 0x34d3 PRODUCT_ID = 0x1100 ?

### ISSUE THREAD

**Issue by raghulkrishna** [Algorithm0/deepcool-digital-info#1]
How to get VENDOR_ID = 0x34d3 PRODUCT_ID = 0x1100 ? i have deepcool ak620 digital would love to know how you implemented this

**Comment by Algorithm0** [comment]
> How to get VENDOR_ID = 0x34d3 PRODUCT_ID = 0x1100 ? i have deepcool ak620 digital would love to know how you implemented this

Hello! Welcome. As I actually said, luck and overkill will help you. Run the superuser rights utility `sudo lsusb -v`. Study the list carefully, step by the elimination method. I'm not sure what will work with your sustainable, but let's try to get it to work together! Try it yourself or send the output of the team here - we will guess together.

**Comment by Algorithm0** [comment]
You can go this way:
1. Enter the command `lsusb`. Pay attention to those devices that are recorded as unknown: unknown;
![Screenshot_20240126-022238](https://github.com/Algorithm0/deepcool-digital-info/assets/39429907/838270a9-f012-4907-82be-7a3879e6b1df)
2. Enter the command `lsusb -d YOUR_VENDOR_ID:YOUR_DEVICE_ID -v`, pay attention to the output. I have this (as you can see in the screenshot above) `lsusb -d 34d3:1100 -v`. It looks like this to me:
```
Bus 001 Device 008: ID 34d3:1100 [unknown] [unknown]
Couldn't open device, some information will be missing  Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 [unknown]
  bDeviceSubClass         0 [unknown]
  bDeviceProtocol         0
  bMaxPacketSize0         8
  idVendor           0x34d3 [unknown]
  idProduct          0x1100 [unknown]
  bcdDevice            2.00                             
  iManufacturer           1 FMD
  iProduct                2 FMD FT072 IAP            
  iSerial                 3 2021-04-02
  bNumConfigurations      1
  Configuration Descriptor:                      
    bLength                 9                              
    bDescriptorType         2
    wTotalLength       0x0029
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0xc0
      Self Powered
    MaxPower              300mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4                          
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         3 Human Interface Device       
      bInterfaceSubClass      0 [unknown]
      bInterfaceProtocol      0                               
      iInterface              0 
          ...
```
3. It is important that here we got that our unknown device is really a hid device (`bInterfaceClass         3 Human Interface Device`). Now we are trying to insert the received data about the vendor and device into my python script. To surely replace with something simpler output by replacing the text after the word 'return' by some constant number.
~~~pythonif
platform == "linux" or platform == "linux2":
    import psutil
    def get_temperature():
        return 15.0
~~~
4. Save and try running. It is necessary to run with superuser rights:
~~~sh
sudo python3 deepcool-digital-info.py
~~~
5. Look carefully at your cooler and clench your fists in the hope that he is about to show you something.

**Comment by raghulkrishna** [comment]
Thank you how did you what payload to be sent? your script for my product gets stuck at while loop

**Comment by Algorithm0** [comment]
> Thank you how did you what payload to be sent? your script for my product gets stuck at while loop

This script is primarily designed to run as a service, because the infinite loop is a foreseen behavior. Tell me, the screen of your cooler began to display a static number?

**Comment by raghulkrishna** [comment]
no there is not activity on the display

**Comment by Algorithm0** [comment]
> no there is not activity on the display

This means you have defined the attributes incorrectly. Unfortunately, I can’t help you here anymore; I’ve described everything on how to look for them. It takes time and patience to sort through the possible values. And yes, to stop the script after starting, to exit the endless loop, just press Control + C.

**Comment by raghulkrishna** [comment]
i figured it out here https://github.com/raghulkrishna/deepcool-ak620-digital-linux thanks
