### ISSUE TITLE
The script doesn't seem to work with AG400 Digital BK 

### ISSUE THREAD

**Issue by Rapozildo57** [Algorithm0/deepcool-digital-info#5]
I have an AG400 Digital BK and, although it works when I install this driver, it shows a left zero (instead of 50ºC it shows 05ºC).
This is the one I've got: https://pt.aliexpress.com/item/1005006504379878.html?gatewayAdapt=glo2bra

I run the "CUSTOM" preset:
"CUSTOM": DeviceInfo(vendor_id=0x3633, product_id=0x0008, simple_mode=False).

Are there any more/better info I can share? I'm really a newbie.

**Comment by digitalinferno** [comment]
AG400 is not supported at this time.

First, try running `sudo lsusb | grep DeepCool`

**Comment by Rapozildo57** [comment]
Here's the info:
$ sudo lsusb | grep DeepCool 
Bus 001 Device 004: ID 3633:0008 DeepCool AG-DIGITAL
