### ISSUE TITLE
Systemctl dependancy

### ISSUE THREAD

**Issue by gelato** [Algorithm0/deepcool-digital-info#9]
Currently this depends heavily on systemctl in both compilation and installation. Would be great to include simple binary installation method (script in this case) for systems which do not have systemctl (like Unraid).

**Comment by Algorithm0** [comment]
I don't plan to expand the current repository to support small popular distributions. I don't use these. Setting up virtual machines for implementation seems to me too much work. If you take over the implementation, I will gladly accept your merge request. In addition, if you own such a system, then it should not be difficult, it is unlikely that you will need to change the python scripts.
